q2:
	mainframer.sh 'cd os && make clean'
	mainframer.sh 'cd os && make default'
	mainframer.sh 'cd apps/q2 && make clean'
	mainframer.sh 'cd apps/q2 && make'
	mainframer.sh 'cd apps/q2 && make run'

q3:
	mainframer.sh 'cd os && make clean'
	mainframer.sh 'cd os && make default'
	mainframer.sh 'cd apps/lottery_test && make clean'
	mainframer.sh 'cd apps/lottery_test && make'
	mainframer.sh 'cd apps/lottery_test && make run'	

clean:
	mainframer.sh 'cd os && make clean'
	mainframer.sh 'cd apps/lottery_test && make clean'
	mainframer.sh 'cd apps/q2 && make clean'
	mainframer.sh 'cd apps/example && make clean'